language: c
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libx11-dev
      - libxt-dev
      - libimlib2-dev
      - libxinerama-dev
      - libjpeg-progs
      - libtest-command-perl
      - libtest-simple-perl
script:
  - make
  - make test
compiler:
  - clang
  - gcc
